apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: pyweb
    mod: httping
  name: pyweb-ping
spec:
  containers:
  - image: python:3.8-alpine
    command: ["/bin/sh","-c"]
    args: 
    - pip install requests;/bin/sleep infinity
    name: httping
    env:
    - name: PYWEB_URL
      value: "http://pyweb-service:8080"
    resources: {}
    volumeMounts:
    - name: script
      mountPath: /tmp/httping.py
      subPath: httping.py
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  terminationGracePeriodSeconds: 0
  volumes:
  - name: script
    configMap:
      name: httping-script
status: {}
